# Site settings
author: Jared Grove
title: THE BLOG
header-img: img/home-bg.png
email: jaredkgrove@gmail.com
copyright_name: Jared Grove
description: > # this means to ignore newlines until "baseurl:"
  this is a story all about how my life got flipped turned upside down
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jaredkgrove

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
